/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Startup = {
  _id: string;
  _type: "startup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  slug?: string;
  views?: number;
  description?: string;
  category?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  keywords?: Array<string>;
  pitch?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  username?: string;
  email?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type Markdown = string;

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = Startup | Author | Markdown | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: STARTUPS_QUERY
// Query: *[_type == "startup" &&     (      !defined($query) ||      lower(title) match "*" + lower($query) + "*" ||      lower(category) match "*" + lower($query) + "*" ||      lower(author->name) match "*" + lower($query) + "*"    )  ] | order(_createdAt desc) {  _id,   title,   slug,  _createdAt,  author -> {    name, image, username  },   views,  description,  category,  image,}
export type STARTUPS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  _createdAt: string;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    username: string | null;
  } | null;
  views: number | null;
  description: string | null;
  category: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: STARTUP_BY_SLUG_QUERY
// Query: *[_type == "startup" && slug == $slug][0]{  _createdAt,  _id,  author -> {    name, image, bio, username, _id, email  },  category,  description,  image,  pitch,  slug,  title,  keywords,  views}
export type STARTUP_BY_SLUG_QUERYResult = {
  _createdAt: string;
  _id: string;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
    username: string | null;
    _id: string;
    email: string | null;
  } | null;
  category: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  pitch: string | null;
  slug: string | null;
  title: string | null;
  keywords: Array<string> | null;
  views: number | null;
} | null;
// Variable: STARTUP_VIEWS_BY_ID_QUERY
// Query: *[_type == "startup" && _id == $id][0]{    _id, views  }
export type STARTUP_VIEWS_BY_ID_QUERYResult = {
  _id: string;
  views: number | null;
} | null;
// Variable: AUTHOR_BY_EMAIL_QUERY
// Query: *[_type == "author" && email == $email][0] {  _id,  name,  email,  username,  image,  bio}
export type AUTHOR_BY_EMAIL_QUERYResult = {
  _id: string;
  name: string | null;
  email: string | null;
  username: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: string | null;
} | null;
// Variable: AUTHOR_BY_USERNAME_QUERY
// Query: *[_type == "author" && username == $username][0] {  _id,  name,  email,  username,  image,  bio}
export type AUTHOR_BY_USERNAME_QUERYResult = {
  _id: string;
  name: string | null;
  email: string | null;
  username: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: string | null;
} | null;
// Variable: AUTHOR_BY_ID_QUERY
// Query: *[_type == "author" && _id == $id][0] {  _id,  name,  email,  username,  image,  bio}
export type AUTHOR_BY_ID_QUERYResult = {
  _id: string;
  name: string | null;
  email: string | null;
  username: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  bio: string | null;
} | null;
// Variable: STARTUPS_BY_AUTHOR_QUERY
// Query: *[_type == "startup" && author._ref == $id] | order(_createdAt desc) {  _id,   title,   slug,  _createdAt,  author -> {    _id, name, image, bio, username, email  },   views,  description,  category,  image,}
export type STARTUPS_BY_AUTHOR_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  _createdAt: string;
  author: {
    _id: string;
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
    username: string | null;
    email: string | null;
  } | null;
  views: number | null;
  description: string | null;
  category: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;
// Variable: AUTHOR_BY_STARTUP_ID_QUERY
// Query: *[_type=="startup" && _id == $id][0] {  author -> {    _id, email, name, username  } }
export type AUTHOR_BY_STARTUP_ID_QUERYResult = {
  author: {
    _id: string;
    email: string | null;
    name: string | null;
    username: string | null;
  } | null;
} | null;
// Variable: RECOMMENDED_STARTUP_QUERY
// Query: *[_type == "startup" && _id != $id && count((keywords[])[@ in $keywords]) > 0] {   _createdAt,  _id,  author -> {    name, image, bio, username, _id, email  },  category,  description,  image,  pitch,  slug,  title,  keywords,  views}| order(count((keywords[])[@ in $keywords]) desc)[0...10]
export type RECOMMENDED_STARTUP_QUERYResult = Array<{
  _createdAt: string;
  _id: string;
  author: {
    name: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
    username: string | null;
    _id: string;
    email: string | null;
  } | null;
  category: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  pitch: string | null;
  slug: string | null;
  title: string | null;
  keywords: Array<string> | null;
  views: number | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"startup\" && \n    (\n      !defined($query) ||\n      lower(title) match \"*\" + lower($query) + \"*\" ||\n      lower(category) match \"*\" + lower($query) + \"*\" ||\n      lower(author->name) match \"*\" + lower($query) + \"*\"\n    )\n  ] | order(_createdAt desc) {\n  _id, \n  title, \n  slug,\n  _createdAt,\n  author -> {\n    name, image, username\n  }, \n  views,\n  description,\n  category,\n  image,\n}": STARTUPS_QUERYResult;
    "*[_type == \"startup\" && slug == $slug][0]{\n  _createdAt,\n  _id,\n  author -> {\n    name, image, bio, username, _id, email\n  },\n  category,\n  description,\n  image,\n  pitch,\n  slug,\n  title,\n  keywords,\n  views\n} ": STARTUP_BY_SLUG_QUERYResult;
    "\n  *[_type == \"startup\" && _id == $id][0]{\n    _id, views\n  }\n": STARTUP_VIEWS_BY_ID_QUERYResult;
    "\n*[_type == \"author\" && email == $email][0] {\n  _id,\n  name,\n  email,\n  username,\n  image,\n  bio\n}\n": AUTHOR_BY_EMAIL_QUERYResult;
    "\n*[_type == \"author\" && username == $username][0] {\n  _id,\n  name,\n  email,\n  username,\n  image,\n  bio\n}\n": AUTHOR_BY_USERNAME_QUERYResult;
    "\n*[_type == \"author\" && _id == $id][0] {\n  _id,\n  name,\n  email,\n  username,\n  image,\n  bio\n}\n": AUTHOR_BY_ID_QUERYResult;
    "*[_type == \"startup\" && author._ref == $id] | order(_createdAt desc) {\n  _id, \n  title, \n  slug,\n  _createdAt,\n  author -> {\n    _id, name, image, bio, username, email\n  }, \n  views,\n  description,\n  category,\n  image,\n}": STARTUPS_BY_AUTHOR_QUERYResult;
    "*[_type==\"startup\" && _id == $id][0] {\n  author -> {\n    _id, email, name, username\n  } \n}\n": AUTHOR_BY_STARTUP_ID_QUERYResult;
    "*[_type == \"startup\" && _id != $id && count((keywords[])[@ in $keywords]) > 0] {\n   _createdAt,\n  _id,\n  author -> {\n    name, image, bio, username, _id, email\n  },\n  category,\n  description,\n  image,\n  pitch,\n  slug,\n  title,\n  keywords,\n  views\n}\n| order(count((keywords[])[@ in $keywords]) desc)[0...10]\n": RECOMMENDED_STARTUP_QUERYResult;
  }
}
