"use client";

import { Button } from "@/components/ui/button";
import {
  Copy,
  FileText,
  Loader,
  MessageSquare,
  RotateCcw,
  ThumbsUp,
} from "lucide-react";
import { useTheme } from "next-themes";
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";
import { useState } from "react";
import Image from "next/image";
import { toast } from "react-toastify";
import { StartupCardType } from "@/types";

const ActionBar = ({ post }: { post: StartupCardType }) => {
  const { theme } = useTheme();
  const [summary, setSummary] = useState<string | null>(null);
  const [summaryLoading, setsummaryLoading] = useState(false);
  const [openSummaryBox, setOpenSummaryBox] = useState(false);

  const copyToClipboard = async () => {
    try {
      if (summary) {
        await navigator.clipboard.writeText(summary);
        toast.success("Summary copied to clipboard", { theme });
      } else {
        toast.error("Nothing to copy", { theme });
      }
    } catch (error) {
      toast.error("Summary copy to clipboard failed", { theme });
    }
  };

  const generateSummary = async () => {
    try {
      setsummaryLoading(true);
      const payload = {
        title: post.title,
        category: post.category,
        description: post.description,
        pitch: post.pitch,
      };
      const raw = await fetch("/api/generate-summary", {
        method: "POST",
        body: JSON.stringify(payload),
        headers: {
          "content-type": "application/json",
        },
      });
      const response = await raw.json();

      if (response.success) {
        setSummary(response.data);
        setsummaryLoading(false);
      } else {
        setsummaryLoading(false);
        setOpenSummaryBox(false);
        toast.error("Something went wrong, try again later", { theme });
      }
    } catch (err) {
      setsummaryLoading(false);
      setOpenSummaryBox(false);
      toast.error("Something wnet wrong, try again later", { theme });
    }
  };

  if (!post) return null;
  return (
    <div className="w-full flex items-center justify-between gap-2 mt-6">
      <Button
        variant="outline"
        className="md:flex-1 py-5 text-sm flex items-center gap-2 hover:bg-primary cursor-pointer rounded-xl font-bold shadow-xl border-2 border-zinc-600"
      >
        <ThumbsUp className="h-4 w-4" />
        Like
      </Button>

      <Dialog open={openSummaryBox} onOpenChange={setOpenSummaryBox}>
        <DialogTrigger asChild>
          <Button
            variant="outline"
            className="flex-1 py-5 text-sm flex items-center flex-col  gap-0 cursor-pointer rounded-xl font-bold shadow-xl border-2 border-zinc-600 bg-gradient-to-r from-sky-100 via-cyan-100 to-blue-100 hover:from-sky-300 hover:via-cyan-300 hover:to-blue-300"
            onClick={generateSummary}
          >
            <div className="flex gap-1">
              <FileText className="h-4 w-4 text-black dark:text-white" />
              <span className="text-black dark:text-white">Summary</span>
            </div>

            <span className="text-[10px] text-black-100 dark:text-white-100 flex items-center gap-1">
              Generated by AI
              <div className="flex">
                <Image
                  src={"/gemini_ai_icon.png"}
                  alt="AI Icon"
                  height={9}
                  width={9}
                />
              </div>
            </span>
          </Button>
        </DialogTrigger>

        {/* DIALOG CONTENT */}
        <DialogContent className="max-w-2xl bg-white font-black rounded-xl">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold flex gap-2 items-center ">
              Startup Summary
              <div className="flex">
                <Image
                  src={"/gemini_ai_icon.png"}
                  alt="AI Icon"
                  height={18}
                  width={18}
                />
                <span className="text-zinc-500 text-[7px]">Powered by AI</span>
              </div>
            </DialogTitle>
          </DialogHeader>

          <div className="mt-4 text-sm text-gray-700 space-y-4">
            <p>
              {post.title} by {post.author?.name}
            </p>

            <div className="p-3 bg-gray-100 rounded-lg">
              {summaryLoading ? (
                <div className="flex gap-4 items-center">
                  <span>Generating ...</span>
                  <Loader className="animate-spin" />
                </div>
              ) : (
                <p>{summary}</p>
              )}
            </div>
          </div>

          {!summaryLoading && (
            <DialogFooter>
              <Button
                onClick={copyToClipboard}
                className="rounded-xl cursor-pointer hover:bg-neutral"
              >
                <Copy className="w-4 h-4" /> Copy to clipboard
              </Button>
              <Button
                onClick={generateSummary}
                className="rounded-xl cursor-pointer hover:bg-neutral"
              >
                <RotateCcw className="w-4 h-4" /> Regenerate
              </Button>
            </DialogFooter>
          )}
        </DialogContent>
      </Dialog>

      <Button
        variant="outline"
        className="md:flex-1 py-5 text-sm flex items-center gap-2 hover:bg-primary cursor-pointer rounded-xl font-bold shadow-xl border-2 border-zinc-600"
      >
        <MessageSquare className="h-4 w-4" />
        Comment
      </Button>
    </div>
  );
};

export default ActionBar;
